# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://straycatcoder.github.io"

# The name of this wonderful theme ;-).
theme = 'PaperMod'

# Basic metadata configuration for your blog.
title = "Stray ฅ^•ﻌ•^ฅ Coder"
author = "Jane Doe"
copyright = "No Copyright © !!!."
[languages]
  [languages.en]
    locale = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[permalinks]
  blog = "/:slug/"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 100

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 110

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 120

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Hugo + PaperMod"
  
  # PaperMod specific settings
  defaultTheme = "auto" # dark, light, or auto
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = true
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    title = "Welcome to the Blog"
    Content = """
Nothing serious on this blog, just random thoughts, coding experiments, and loads of nonsense.
    """

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/straycatcoder"

  [[params.socialIcons]]
    name = "rss"
    url = "/blog/index.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"] # is necessary for search

# Configure markup highlighter
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
